apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2019-07-12T16:17:56Z"
  labels:
    app: synopsys-operator
    component: operator
  name: synopsys-operator-admin
  namespace: so-one
  resourceVersion: "2555"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/so-one/roles/synopsys-operator-admin
  uid: 9f353ccd-9d01-4ec7-9056-9fb4b2ecdb57
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - batch
  - extensions
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  - deployments/scale
  - deployments/rollback
  - statefulsets
  - statefulsets/scale
  - replicasets
  - replicasets/scale
  - daemonsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - ""
  resources:
  - namespaces
  - configmaps
  - persistentvolumeclaims
  - services
  - secrets
  - replicationcontrollers
  - replicationcontrollers/scale
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - endpoints
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - synopsys.com
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  - volumeattachments
  verbs:
  - get
  - list
  - watch
